lsi: false
safe: true
Configuration file: /home/jeongyj/personalProject/danielyj147.github.io/_config.yml
source: /home/jeongyj/personalProject/danielyj147.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge